'use client';
import{useState,useCallback,useRef,useEffect}from'react';
const RG=['Global','India','Asia','Europe','Africa','Americas','Oceania'];
const HB=['All','Forest','Wetland','Urban','Grassland','Coastal'];
const NV=['Quest','Learn','Profile'];
export default function Home(){
const[screen,setScreen]=useState('home');
const[phase,setPhase]=useState('listen');
const[nav,setNav]=useState('Quest');
const[region,setRegion]=useState('India');
const[habitat,setHab]=useState('All');
const[score,setScore]=useState(0);
const[streak,setStreak]=useState(0);
const[best,setBest]=useState(0);
const[qn,setQn]=useState(0);
const[question,setQ]=useState(null);
const[loading,setLoading]=useState(false);
const[sel,setSel]=useState(null);
const[ok,setOk]=useState(null);
const[playing,setPlaying]=useState(false);
const[audioReady,setAR]=useState(false);
const[imgLoaded,setIL]=useState(false);
const[imgErr,setIE]=useState(false);
const[xp,setXp]=useState(0);
const[totalXp,setTotalXp]=useState(0);
const[discovered,setDiscovered]=useState([]);
const[totalPlayed,setTP]=useState(0);
const[totalCorrect,setTC]=useState(0);
const[learnBird,setLB]=useState(null);
const[learnLoading,setLL]=useState(false);
const[autoPlay,setAutoPlay]=useState(true);
const[slide,setSlide]=useState('');
const aRef=useRef(null);
useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('bcq')||'{}');if(p.xp)setTotalXp(p.xp);if(p.disc)setDiscovered(p.disc);if(p.tp)setTP(p.tp);if(p.tc)setTC(p.tc);if(p.bs)setBest(p.bs);}catch(e){}},[]);
const save=(nx,nd,np,nc,nb)=>{try{localStorage.setItem('bcq',JSON.stringify({xp:nx,disc:nd,tp:np,tc:nc,bs:nb}));}catch(e){}};
const goTo=(s)=>{setSlide('slide-out');setTimeout(()=>{setScreen(s);setSlide('slide-in');setTimeout(()=>setSlide(''),400);},300);};
const fetchQ=useCallback(async()=>{setLoading(true);setSel(null);setOk(null);setAR(false);setPlaying(false);setIL(false);setIE(false);setPhase('listen');if(aRef.current){aRef.current.pause();aRef.current=null;}try{const res=await fetch(`/api/question?region=${encodeURIComponent(region)}&habitat=${encodeURIComponent(habitat)}`);const data=await res.json();setQ(data);setQn(q=>q+1);setLoading(false);if(data.audioUrl){const a=new Audio(data.audioUrl);a.addEventListener('canplaythrough',()=>{setAR(true);if(autoPlay){setPlaying(true);a.play().catch(()=>{});}},{once:true});a.addEventListener('ended',()=>setPlaying(false));a.addEventListener('error',()=>setAR(false));a.load();aRef.current=a;}}catch(e){setLoading(false);}},[region,habitat,autoPlay]);
const playA=()=>{if(!aRef.current)return;if(playing){aRef.current.pause();setPlaying(false);}else{aRef.current.play().catch(()=>{});setPlaying(true);aRef.current.onended=()=>setPlaying(false);}};
const pick=(id)=>{if(sel!==null||!question)return;const c=id===question.correctId;setSel(id);setOk(c);const np=totalPlayed+1;const nc=totalCorrect+(c?1:0);let ns=streak,nb=best,ex=5;if(c){ns=streak+1;ex=ns>=3?30:ns>=2?20:10;nb=Math.max(best,ns);setScore(s=>s+1);setStreak(ns);}else{ns=0;setStreak(0);}setBest(nb);setXp(x=>x+ex);const nx=totalXp+ex;setTotalXp(nx);setTP(np);setTC(nc);let nd=[...discovered];const b=question.bird;if(b&&!nd.includes(b.id)){nd.push(b.id);setDiscovered(nd);}save(nx,nd,np,nc,nb);setPhase('reveal');setTimeout(()=>setPhase('birdpage'),2200);};
const fetchLB=async()=>{setLL(true);setIL(false);setIE(false);setAR(false);setPlaying(false);if(aRef.current){aRef.current.pause();aRef.current=null;}try{const res=await fetch(`/api/question?region=${encodeURIComponent(region)}&habitat=${encodeURIComponent(habitat)}`);const data=await res.json();setLB(data.bird);setLL(false);if(data.bird?.audioUrl){const a=new Audio(data.bird.audioUrl);a.addEventListener('canplaythrough',()=>setAR(true),{once:true});a.addEventListener('ended',()=>setPlaying(false));a.load();aRef.current=a;}}catch(e){setLL(false);}};
const bird=question?.bird;
const level=Math.floor(totalXp/100)+1;
const lvlProg=(totalXp%100);
const bg={background:'linear-gradient(165deg,#080f1c 0%,#0c1a2e 40%,#0f2235 70%,#080f1c 100%)'};
const glass={background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)'};
const pill=(on)=>on?'bg-emerald-500 text-white shadow-lg shadow-emerald-500/20':'text-slate-400 hover:text-slate-200 hover:bg-white/5';
const pillS=(on)=>on?{}:{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.08)'};
const Nav=()=>(<nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 lg:px-10 py-4" style={{background:'rgba(8,15,28,0.85)',backdropFilter:'blur(20px)',borderBottom:'1px solid rgba(255,255,255,0.06)'}}><span className="text-emerald-400 font-black text-lg cursor-pointer" style={{fontFamily:"'Playfair Display',Georgia,serif"}} onClick={()=>goTo('home')}>BirdCall Quest</span><div className="hidden md:flex gap-1">{NV.map(i=>(<button key={i} onClick={()=>{setNav(i);if(i==='Quest')goTo('home');if(i==='Learn')goTo('learn');if(i==='Profile')goTo('profile');}} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${nav===i?'text-emerald-400':'text-slate-400 hover:text-slate-200'}`}>{i}</button>))}</div><div className="flex items-center gap-3">{screen==='play'&&<div className="flex gap-4 mr-2"><div className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-500">Score</div><div className="text-lg font-bold text-emerald-400">{score}</div></div><div className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-500">Streak</div><div className={`text-lg font-bold ${streak>=3?'text-amber-400':'text-slate-400'}`}>{streak>=3?streak+' 🔥':streak}</div></div></div>}<div className="px-3 py-1 rounded-full text-xs font-bold" style={{background:'rgba(251,191,36,0.1)',border:'1px solid rgba(251,191,36,0.2)',color:'#fbbf24'}}>Lv.{level}</div><div className="w-9 h-9 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center text-xs font-bold text-white cursor-pointer" onClick={()=>goTo('profile')}>B</div></div></nav>);

if(screen==='profile')return(<div className={`min-h-screen text-gray-100 ${slide}`} style={bg}><Nav/><div className="pt-24 pb-10 max-w-2xl mx-auto px-4">
<div className="text-center mb-8"><div className="w-20 h-20 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center text-3xl font-bold text-white mx-auto mb-4">B</div>
<h2 className="text-2xl font-bold text-white" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>Birder Profile</h2>
<p className="text-emerald-400 font-bold mt-1">Level {level} · {totalXp} XP</p>
<div className="w-48 h-2 rounded-full mx-auto mt-3 overflow-hidden" style={{background:'rgba(255,255,255,0.05)'}}><div className="h-full rounded-full" style={{width:lvlProg+'%',background:'linear-gradient(90deg,#10b981,#fbbf24)'}}/></div>
<p className="text-xs text-slate-500 mt-1">{100-lvlProg} XP to Level {level+1}</p></div>
<div className="grid grid-cols-2 gap-4 mb-6">
{[{l:'Birds Discovered',v:discovered.length+'/150',icon:'🐦',c:'text-emerald-400'},{l:'Total Games',v:totalPlayed,icon:'🎮',c:'text-blue-400'},{l:'Accuracy',v:totalPlayed?Math.round(totalCorrect/totalPlayed*100)+'%':'--',icon:'🎯',c:'text-purple-400'},{l:'Best Streak',v:best,icon:'🔥',c:'text-amber-400'}].map((x,i)=>(<div key={i} className="p-4 rounded-2xl text-center" style={glass}><div className="text-2xl mb-2">{x.icon}</div><div className={`text-xl font-bold ${x.c}`}>{x.v}</div><div className="text-[10px] uppercase tracking-wider text-slate-500 mt-1">{x.l}</div></div>))}</div>
<div className="rounded-2xl p-5 mb-6" style={glass}><div className="text-[11px] uppercase tracking-[0.15em] text-slate-500 font-bold mb-4">⚙️ Settings</div>
<div className="flex items-center justify-between py-3" style={{borderBottom:'1px solid rgba(255,255,255,0.05)'}}><span className="text-sm text-slate-300">Auto-play bird calls</span><button onClick={()=>setAutoPlay(!autoPlay)} className={`w-12 h-6 rounded-full transition-all relative ${autoPlay?'bg-emerald-500':'bg-slate-700'}`}><div className={`w-5 h-5 rounded-full bg-white absolute top-0.5 transition-all ${autoPlay?'left-[26px]':'left-0.5'}`}/></button></div>
<div className="flex items-center justify-between py-3"><span className="text-sm text-slate-300">Default Region</span><span className="text-sm text-emerald-400 font-medium">{region}</span></div></div>
<button onClick={()=>{try{localStorage.removeItem('bcq');}catch(e){}setTotalXp(0);setDiscovered([]);setTP(0);setTC(0);setBest(0);}} className="w-full py-3 rounded-xl text-red-400 text-sm font-medium hover:bg-red-500/5" style={{border:'1px solid rgba(239,68,68,0.15)'}}>Reset All Progress</button>
<button onClick={()=>goTo('home')} className="w-full mt-3 py-3 rounded-xl text-slate-400 text-sm font-medium hover:text-slate-200" style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.06)'}}>← Back to Sanctuary</button>
</div></div>);
if(screen==='learn')return(<div className={`min-h-screen text-gray-100 ${slide}`} style={bg}><Nav/><div className="pt-24 pb-10 max-w-2xl mx-auto px-4">
<div className="mb-6"><h2 className="text-3xl font-bold text-white mb-2" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>📖 Learn Mode</h2><p className="text-slate-400 text-sm">Browse birds, listen to their calls, and study before you quiz.</p></div>
<div className="grid grid-cols-2 gap-3 mb-6"><div className="rounded-2xl p-4" style={glass}><div className="text-[10px] uppercase tracking-wider text-slate-500 font-bold mb-2">Region</div><div className="flex flex-wrap gap-1.5">{RG.map(r=>(<button key={r} onClick={()=>setRegion(r)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${pill(region===r)}`} style={pillS(region===r)}>{r}</button>))}</div></div><div className="rounded-2xl p-4" style={glass}><div className="text-[10px] uppercase tracking-wider text-slate-500 font-bold mb-2">Habitat</div><div className="flex flex-wrap gap-1.5">{HB.map(h=>(<button key={h} onClick={()=>setHab(h)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${pill(habitat===h)}`} style={pillS(habitat===h)}>{h==='All'?'All':h}</button>))}</div></div></div>
{!learnBird&&!learnLoading&&<div className="text-center py-16"><button onClick={fetchLB} className="px-8 py-4 rounded-2xl text-white text-lg font-bold flex items-center gap-3 mx-auto active:scale-[0.97]" style={{background:'linear-gradient(135deg,#3b82f6,#60a5fa)',boxShadow:'0 8px 32px rgba(59,130,246,0.3)'}}>Explore a Bird <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button></div>}
{learnLoading&&<div className="text-center py-16"><div className="w-10 h-10 border-[3px] border-blue-500/20 border-t-blue-500 rounded-full mx-auto mb-5" style={{animation:'spin .8s linear infinite'}}/><p className="text-slate-400 text-sm">Finding a bird for you...</p></div>}
{learnBird&&!learnLoading&&(<div style={{animation:'fadeUp 0.5s ease-out'}}>
<div className="rounded-2xl overflow-hidden mb-6" style={{border:'1px solid rgba(255,255,255,0.07)'}}><div className="relative w-full min-h-[240px] flex items-center justify-center" style={{background:'rgba(0,0,0,0.3)'}}>{learnBird.imageUrl&&!imgErr?(<>{!imgLoaded&&<div className="absolute inset-0 flex items-center justify-center"><div className="w-8 h-8 border-[3px] border-blue-500/20 border-t-blue-500 rounded-full" style={{animation:'spin .8s linear infinite'}}/></div>}<img src={learnBird.imageUrl} alt={learnBird.en} onLoad={()=>setIL(true)} onError={()=>setIE(true)} className={`w-full max-h-96 object-cover ${imgLoaded?'block':'hidden'}`}/><div className="absolute bottom-0 inset-x-0 px-4 py-2" style={{background:'linear-gradient(transparent,rgba(0,0,0,0.7))'}}><p className="text-[10px] text-white/40 text-right">📷 {learnBird.imageCredit||'Wikimedia'} · CC BY-SA</p></div></>):(<div className="py-16 text-slate-600 text-sm">No photo available</div>)}</div></div>
<h2 className="text-3xl font-bold text-white mb-1" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>{learnBird.en}</h2><p className="text-base text-blue-400 italic mb-4">{learnBird.sci}</p><p className="text-base text-slate-300 leading-relaxed mb-5">{learnBird.desc}</p>
<div className="rounded-2xl p-5 mb-5" style={glass}><div className="flex items-center gap-4"><button onClick={playA} disabled={!audioReady} className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${audioReady?'text-white':'text-slate-500'}`} style={audioReady?{background:'linear-gradient(135deg,#3b82f6,#60a5fa)'}:{background:'rgba(255,255,255,0.04)'}}><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">{playing?<><rect x="6" y="4" width="4" height="16" rx="1"/><rect x="14" y="4" width="4" height="16" rx="1"/></>:<polygon points="5,3 19,12 5,21"/>}</svg></button><div><div className="text-sm font-semibold text-slate-200">{playing?'Playing...':audioReady?'Tap to listen':'Loading call...'}</div>{learnBird.recordist&&<div className="text-xs text-slate-500">{learnBird.recordist} · xeno-canto</div>}</div></div></div>
<div className="grid grid-cols-2 gap-3 mb-5"><div className="p-4 rounded-2xl" style={{background:'rgba(168,85,247,0.04)',border:'1px solid rgba(168,85,247,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-purple-400 font-bold mb-2">🔍 Features</div><div className="text-sm text-slate-300">{learnBird.features}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(96,165,250,0.04)',border:'1px solid rgba(96,165,250,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-blue-400 font-bold mb-2">🌍 Found In</div><div className="text-sm text-slate-300">{learnBird.regions?.join(' · ')}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(52,211,153,0.04)',border:'1px solid rgba(52,211,153,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-emerald-400 font-bold mb-2">🌿 Habitat</div><div className="text-sm text-slate-300">{learnBird.habitats?.map(h=>h.charAt(0).toUpperCase()+h.slice(1)).join(' · ')}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(251,191,36,0.04)',border:'1px solid rgba(251,191,36,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-amber-400 font-bold mb-2">✨ Fun Fact</div><div className="text-sm text-slate-300">{learnBird.funFact}</div></div></div>
<button onClick={()=>{setLB(null);setIL(false);setIE(false);fetchLB();}} className="w-full py-4 rounded-2xl text-white font-bold text-lg flex items-center justify-center gap-3 active:scale-[0.97] mb-3" style={{background:'linear-gradient(135deg,#3b82f6,#60a5fa)',boxShadow:'0 8px 32px rgba(59,130,246,0.25)'}}>Next Bird <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button></div>)}
<button onClick={()=>goTo('home')} className="w-full mt-3 py-3 rounded-xl text-slate-400 text-sm font-medium hover:text-slate-200" style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.06)'}}>← Back to Sanctuary</button></div></div>);
if(screen==='home')return(<div className={`min-h-screen text-gray-100 ${slide}`} style={bg}><Nav/><div className="pt-20">
<div className="relative mx-4 lg:mx-10 rounded-2xl overflow-hidden" style={{minHeight:'420px'}}><div className="absolute inset-0" style={{background:'url(https://images.unsplash.com/photo-1448375240586-882707db888b?w=1400&q=80) center/cover'}}/><div className="absolute inset-0" style={{background:'linear-gradient(180deg,rgba(8,15,28,0.3) 0%,rgba(8,15,28,0.6) 60%,rgba(8,15,28,0.95) 100%)'}}/><div className="relative flex flex-col items-center justify-center text-center px-6 py-24 lg:py-32"><h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-4" style={{fontFamily:"'Playfair Display',Georgia,serif",color:'#a8edce',textShadow:'0 0 80px rgba(52,211,153,0.15)'}}>The Digital Sanctuary</h1><p className="text-slate-300 text-base md:text-lg max-w-xl leading-relaxed">Embark on a journey to discover and identify birds by their unique calls in the wild.</p></div></div>
<div className="grid md:grid-cols-2 gap-4 mx-4 lg:mx-10 mt-6"><div className="rounded-2xl p-6" style={{...glass,backdropFilter:'blur(12px)'}}><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 4 10 15 15 0 0 1-4 10 15 15 0 0 1-4-10A15 15 0 0 1 12 2z"/></svg></div><h3 className="text-white font-semibold text-lg">Select Region</h3></div><div className="flex flex-wrap gap-2">{RG.map(r=>(<button key={r} onClick={()=>setRegion(r)} className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${pill(region===r)}`} style={pillS(region===r)}>{r}</button>))}</div></div><div className="rounded-2xl p-6" style={{...glass,backdropFilter:'blur(12px)'}}><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#60a5fa" strokeWidth="2" strokeLinecap="round"><path d="M8 21l4-4 4 4"/><path d="M4 15l8-8 8 8"/></svg></div><h3 className="text-white font-semibold text-lg">Choose Habitat</h3></div><div className="flex flex-wrap gap-2">{HB.map(h=>(<button key={h} onClick={()=>setHab(h)} className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${pill(habitat===h)}`} style={pillS(habitat===h)}>{h==='All'?'All Habitats':h}</button>))}</div></div></div>
<div className="mx-4 lg:mx-10 mt-6 rounded-2xl p-6 md:p-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6" style={glass}><div><h2 className="text-2xl md:text-3xl font-bold text-white mb-2" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>Ready for the Expedition?</h2><p className="text-slate-400 text-sm md:text-base">Current settings: <span className="text-emerald-400 font-medium">{region} {habitat==='All'?'':habitat}</span>. We&apos;ve found <span className="text-emerald-400 font-medium">150</span> bird species.</p></div><button onClick={()=>{setScore(0);setStreak(0);setQn(0);setXp(0);setNav('Quest');goTo('play');setTimeout(fetchQ,400);}} className="flex-shrink-0 px-8 py-4 rounded-2xl text-white text-lg font-bold flex items-center gap-3 active:scale-[0.97]" style={{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 8px 32px rgba(16,185,129,0.3)'}}>Start Quest <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button></div>
<div className="grid grid-cols-2 gap-4 mx-4 lg:mx-10 mt-6"><button onClick={()=>{setNav('Learn');goTo('learn');}} className="rounded-2xl p-5 text-left transition-all hover:scale-[1.01]" style={{background:'rgba(59,130,246,0.05)',border:'1px solid rgba(59,130,246,0.12)'}}><div className="text-2xl mb-2">📖</div><div className="font-bold text-white text-base mb-1">Learn Mode</div><div className="text-xs text-slate-400">Browse birds, listen & study</div></button><button onClick={()=>{setNav('Profile');goTo('profile');}} className="rounded-2xl p-5 text-left transition-all hover:scale-[1.01]" style={{background:'rgba(251,191,36,0.05)',border:'1px solid rgba(251,191,36,0.12)'}}><div className="text-2xl mb-2">🏆</div><div className="font-bold text-white text-base mb-1">Your Progress</div><div className="text-xs text-slate-400">Lv.{level} · {discovered.length} birds found</div></button></div>
<div className="flex items-center justify-center gap-4 py-10 text-xs"><span className="text-slate-600 uppercase tracking-widest font-medium">Powered by</span><span className="text-slate-500 font-medium">xeno-canto</span><span className="text-slate-700">|</span><span className="text-slate-500 font-medium">Wikimedia Commons</span></div></div></div>);
return(<div className={`min-h-screen text-gray-100 ${slide}`} style={bg}><Nav/><div className="pt-24 pb-10 max-w-2xl mx-auto px-4">
{loading&&<div className="text-center py-24"><div className="w-10 h-10 border-[3px] border-emerald-500/20 border-t-emerald-500 rounded-full mx-auto mb-5" style={{animation:'spin .8s linear infinite'}}/><p className="text-slate-400 text-sm">Fetching a real bird call...</p></div>}
{!loading&&question&&(<div>
{phase==='listen'&&(<div style={{animation:'fadeUp 0.4s ease-out'}}><div className="rounded-2xl p-6 text-center mb-5" style={glass}><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500 font-semibold mb-5">Question {qn} of ∞</div><div className="flex justify-center items-center gap-[3px] h-14 mb-5">{Array.from({length:28}).map((_,i)=>(<div key={i} className="w-[3px] rounded-full" style={{background:playing?'#34d399':'rgba(52,211,153,0.15)',height:playing?'100%':'6px',transformOrigin:'center',animation:playing?`pulse-bar ${0.35+Math.random()*0.5}s ease-in-out ${i*0.035}s infinite`:'none'}}/>))}</div>{!audioReady&&!playing&&<p className="text-xs text-slate-500 mb-3">{question.audioUrl?'Loading...':'No recording'}</p>}<button onClick={playA} disabled={!audioReady} className={`inline-flex items-center gap-3 px-7 py-3 rounded-2xl text-sm font-bold ${playing?'text-emerald-400':audioReady?'text-white':'text-slate-500 cursor-wait'}`} style={playing?{background:'rgba(16,185,129,0.1)',border:'1px solid rgba(16,185,129,0.25)'}:audioReady?{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 6px 24px rgba(16,185,129,0.25)'}:{background:'rgba(255,255,255,0.04)'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">{playing?<><rect x="6" y="4" width="4" height="16" rx="1"/><rect x="14" y="4" width="4" height="16" rx="1"/></>:<polygon points="5,3 19,12 5,21"/>}</svg>{playing?'Pause':audioReady?'Play Call':'Loading...'}</button>{question.recordist&&<p className="text-[11px] text-slate-600 mt-4">🔊 {question.recordist} · xeno-canto</p>}</div>
<div className="grid gap-3">{question.options.map((o,i)=>(<button key={o.id} onClick={()=>pick(o.id)} className="w-full p-4 rounded-2xl text-left flex items-center gap-4 hover:scale-[1.01] transition-all" style={{background:'rgba(255,255,255,0.025)',border:'1px solid rgba(255,255,255,0.06)'}}><span className="w-10 h-10 rounded-xl flex items-center justify-center text-sm font-bold flex-shrink-0" style={{background:'rgba(96,165,250,0.08)',color:'#60a5fa'}}>{String.fromCharCode(65+i)}</span><span className="font-semibold text-slate-200">{o.en}</span></button>))}</div></div>)}
{phase==='reveal'&&bird&&(<div className="fixed inset-0 z-40 flex flex-col items-center justify-center" style={{background:ok?'radial-gradient(circle,rgba(16,185,129,0.15),rgba(8,15,28,0.98))':'radial-gradient(circle,rgba(239,68,68,0.12),rgba(8,15,28,0.98))',animation:'fadeUp 0.3s ease-out'}}>{ok&&<div className="absolute inset-0 overflow-hidden pointer-events-none">{Array.from({length:20}).map((_,i)=>(<div key={i} className="absolute w-2 h-2 rounded-full" style={{background:['#34d399','#fbbf24','#60a5fa','#a78bfa','#f472b6'][i%5],left:Math.random()*100+'%',top:'100%',animation:`confetti ${1+Math.random()*1.5}s ease-out ${i*0.08}s forwards`,opacity:0}}/>))}</div>}<div className={`w-24 h-24 rounded-full flex items-center justify-center text-5xl mb-6 ${ok?'bg-emerald-500':'bg-red-500'}`} style={{animation:'popIn 0.5s cubic-bezier(0.68,-0.55,0.265,1.55)',boxShadow:ok?'0 0 60px rgba(16,185,129,0.4)':'0 0 60px rgba(239,68,68,0.3)'}}>{ok?'✓':'✗'}</div><div className="text-4xl md:text-5xl font-bold mb-3" style={{fontFamily:"'Playfair Display',Georgia,serif",color:ok?'#34d399':'#f87171',animation:'fadeUp 0.4s ease-out 0.2s both'}}>{ok?(streak>=3?'On Fire!':'Correct!'):'Not Quite!'}</div>{ok&&streak>=2&&<div className="text-2xl font-bold text-amber-400 mb-3" style={{animation:'fadeUp 0.4s ease-out 0.3s both'}}>🔥 {streak} Streak!</div>}{!ok&&<div className="text-lg text-slate-400 mb-3" style={{animation:'fadeUp 0.4s ease-out 0.3s both'}}>It was <strong className="text-emerald-400">{bird.en}</strong></div>}<div className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full mt-2" style={{background:'rgba(251,191,36,0.1)',border:'1px solid rgba(251,191,36,0.2)',animation:'fadeUp 0.4s ease-out 0.4s both'}}><span className="text-amber-400 font-bold">+{ok?(streak>=3?30:streak>=2?20:10):5} XP</span></div><p className="text-slate-500 text-sm mt-8" style={{animation:'fadeUp 0.4s ease-out 0.6s both'}}>Discovering bird...</p></div>)}
{phase==='birdpage'&&bird&&(<div style={{animation:'fadeUp 0.5s ease-out'}}>
<div className="rounded-2xl overflow-hidden mb-6" style={{border:'1px solid rgba(255,255,255,0.07)'}}><div className="relative w-full min-h-[260px] flex items-center justify-center" style={{background:'rgba(0,0,0,0.3)'}}>{bird.imageUrl&&!imgErr?(<>{!imgLoaded&&<div className="absolute inset-0 flex items-center justify-center"><div className="w-8 h-8 border-[3px] border-emerald-500/20 border-t-emerald-500 rounded-full" style={{animation:'spin .8s linear infinite'}}/></div>}<img src={bird.imageUrl} alt={bird.en} onLoad={()=>setIL(true)} onError={()=>setIE(true)} className={`w-full max-h-96 object-cover ${imgLoaded?'block':'hidden'}`}/><div className="absolute bottom-0 inset-x-0 px-4 py-2" style={{background:'linear-gradient(transparent,rgba(0,0,0,0.7))'}}><p className="text-[10px] text-white/40 text-right">📷 {bird.imageCredit||'Wikimedia'} · CC BY-SA</p></div></>):(<div className="py-16 text-slate-600 text-sm">No photo available</div>)}</div></div>
<div className="flex items-start justify-between mb-6"><div><div className="text-[11px] uppercase tracking-[0.15em] text-emerald-400 font-bold mb-2">{ok?'✓ Species Identified':'✗ Species Discovered'}</div><h2 className="text-3xl md:text-4xl font-bold text-white mb-1" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>{bird.en}</h2><p className="text-base text-blue-400 italic">{bird.sci}</p></div><div className="px-3 py-1.5 rounded-full text-xs font-bold" style={{background:bird.difficulty==='rare'?'rgba(251,191,36,0.1)':'rgba(52,211,153,0.1)',border:bird.difficulty==='rare'?'1px solid rgba(251,191,36,0.2)':'1px solid rgba(52,211,153,0.2)',color:bird.difficulty==='rare'?'#fbbf24':'#34d399'}}>{bird.difficulty==='rare'?'⭐ Rare':'Common'}</div></div>
<p className="text-base text-slate-300 leading-relaxed mb-6">{bird.desc}</p>
<div className="grid grid-cols-2 gap-3 mb-6"><div className="p-4 rounded-2xl" style={{background:'rgba(168,85,247,0.04)',border:'1px solid rgba(168,85,247,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-purple-400 font-bold mb-2">🔍 Features</div><div className="text-sm text-slate-300">{bird.features}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(96,165,250,0.04)',border:'1px solid rgba(96,165,250,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-blue-400 font-bold mb-2">🌍 Found In</div><div className="text-sm text-slate-300">{bird.regions?.join(' · ')}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(52,211,153,0.04)',border:'1px solid rgba(52,211,153,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-emerald-400 font-bold mb-2">🌿 Habitat</div><div className="text-sm text-slate-300">{bird.habitats?.map(h=>h.charAt(0).toUpperCase()+h.slice(1)).join(' · ')}</div></div><div className="p-4 rounded-2xl" style={{background:'rgba(251,191,36,0.04)',border:'1px solid rgba(251,191,36,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-amber-400 font-bold mb-2">✨ Fun Fact</div><div className="text-sm text-slate-300">{bird.funFact}</div></div></div>
{bird.recordist&&<div className="rounded-2xl p-4 mb-6 flex items-center gap-3" style={glass}><div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-lg">🔊</div><div><div className="text-sm font-semibold text-slate-300">{bird.recordist}</div><div className="text-xs text-slate-500">xeno-canto · {bird.license||'CC'}</div></div></div>}
<div className="rounded-2xl p-5 mb-6" style={glass}><div className="text-[11px] uppercase tracking-[0.15em] text-slate-500 font-bold mb-3">Your Answer</div><div className="grid gap-2">{question.options.map((o,i)=>{const me=o.id===sel,ans=o.id===question.correctId;return(<div key={o.id} className={`flex items-center gap-3 p-3 rounded-xl ${!me&&!ans?'opacity-25':''}`} style={ans?{background:'rgba(16,185,129,0.06)',border:'1px solid rgba(16,185,129,0.2)'}:me&&!ok?{background:'rgba(239,68,68,0.06)',border:'1px solid rgba(239,68,68,0.2)'}:{background:'rgba(255,255,255,0.02)',border:'1px solid rgba(255,255,255,0.04)'}}><span className={`w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold ${ans?'bg-emerald-500 text-white':me&&!ok?'bg-red-500 text-white':'text-slate-500'}`} style={!ans&&!(me&&!ok)?{background:'rgba(255,255,255,0.05)'}:{}}>{ans?'✓':me&&!ok?'✗':String.fromCharCode(65+i)}</span><span className={`text-sm font-semibold ${ans?'text-emerald-400':'text-slate-400'}`}>{o.en}</span></div>);})}</div></div>
<div className="rounded-2xl p-5 mb-6" style={glass}><div className="flex justify-between items-center mb-3"><span className="text-[11px] uppercase tracking-[0.15em] text-slate-500 font-bold">Quest Progress</span><span className="text-amber-400 font-bold text-sm">{xp} XP</span></div><div className="w-full h-2 rounded-full overflow-hidden" style={{background:'rgba(255,255,255,0.05)'}}><div className="h-full rounded-full transition-all duration-1000" style={{width:Math.min(xp,300)/300*100+'%',background:'linear-gradient(90deg,#10b981,#34d399,#fbbf24)'}}/></div><div className="flex justify-between mt-3">{[{l:'Score',v:score+'/'+qn,c:'text-emerald-400'},{l:'Streak',v:streak>=3?streak+' 🔥':String(streak),c:streak>=3?'text-amber-400':'text-slate-400'},{l:'Accuracy',v:(qn?Math.round(score/qn*100):0)+'%',c:'text-slate-200'},{l:'Best',v:best,c:'text-amber-400'}].map((x,i)=>(<div key={i} className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-600">{x.l}</div><div className={`text-sm font-bold ${x.c}`}>{x.v}</div></div>))}</div></div>
<button onClick={fetchQ} className="w-full py-4 rounded-2xl text-white font-bold text-lg flex items-center justify-center gap-3 active:scale-[0.97] mb-3" style={{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 8px 32px rgba(16,185,129,0.25)'}}>Next Bird <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button>
<button onClick={()=>{if(aRef.current)aRef.current.pause();goTo('home');}} className="w-full py-3 rounded-xl text-slate-400 text-sm font-medium hover:text-slate-200" style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.06)'}}>← Back to Sanctuary</button>
</div>)}
</div>)}</div></div>);}
