'use client';
import{useState,useCallback,useRef}from'react';
const R=['Global','India','Asia','Europe','Africa','Americas','Oceania'];
const H=['All','Forest','Wetland','Urban','Grassland','Coastal'];
const NV=['Quest','Collection','Identify','Profile'];
export default function Home(){
const[screen,setScreen]=useState('home');
const[nav,setNav]=useState('Quest');
const[region,setRegion]=useState('India');
const[habitat,setHab]=useState('All');
const[score,setScore]=useState(0);
const[streak,setStreak]=useState(0);
const[best,setBest]=useState(0);
const[qn,setQn]=useState(0);
const[question,setQ]=useState(null);
const[loading,setLoading]=useState(false);
const[sel,setSel]=useState(null);
const[ok,setOk]=useState(null);
const[playing,setPlaying]=useState(false);
const[audioReady,setAR]=useState(false);
const[imgLoaded,setIL]=useState(false);
const[imgErr,setIE]=useState(false);
const ar=useRef(null);
const fetchQ=useCallback(async()=>{
setLoading(true);setSel(null);setOk(null);setAR(false);setPlaying(false);setIL(false);setIE(false);
if(ar.current){ar.current.pause();ar.current=null;}
try{const res=await fetch(`/api/question?region=${encodeURIComponent(region)}&habitat=${encodeURIComponent(habitat)}`);
const data=await res.json();setQ(data);setQn(q=>q+1);setLoading(false);
if(data.audioUrl){const a=new Audio(data.audioUrl);
a.addEventListener('canplaythrough',()=>{setAR(true);setPlaying(true);a.play().catch(()=>{});},{once:true});
a.addEventListener('ended',()=>setPlaying(false));
a.addEventListener('error',()=>setAR(false));
a.load();ar.current=a;}}catch(e){setLoading(false);}},[region,habitat]);
const playA=()=>{if(!ar.current)return;if(playing){ar.current.pause();setPlaying(false);}else{ar.current.play().catch(()=>{});setPlaying(true);ar.current.onended=()=>setPlaying(false);}};
const pick=(id)=>{if(sel!==null||!question)return;const c=id===question.correctId;setSel(id);setOk(c);if(c){setScore(s=>s+1);setStreak(s=>{const n=s+1;setBest(b=>Math.max(b,n));return n;});}else setStreak(0);};
const bird=question?.bird;

const Nav=()=>(<nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 lg:px-10 py-4" style={{background:'rgba(8,15,28,0.85)',backdropFilter:'blur(20px)',borderBottom:'1px solid rgba(255,255,255,0.06)'}}><span className="text-emerald-400 font-black text-lg" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>BirdCall Quest</span><div className="hidden md:flex gap-1">{NV.map(i=>(<button key={i} onClick={()=>{setNav(i);if(i==='Quest')setScreen('home');}} className={`px-4 py-2 rounded-lg text-sm font-medium ${nav===i?'text-emerald-400':'text-slate-400 hover:text-slate-200'}`}>{i}</button>))}</div><div className="flex items-center gap-3">{screen==='play'&&<div className="flex gap-4 mr-2"><div className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-500">Score</div><div className="text-lg font-bold text-emerald-400">{score}</div></div><div className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-500">Streak</div><div className={`text-lg font-bold ${streak>=3?'text-amber-400':'text-slate-400'}`}>{streak>=3?streak+' \uD83D\uDD25':streak}</div></div></div>}<button className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-200 hover:bg-white/5"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg></button><button className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-200 hover:bg-white/5"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/></svg></button><div className="w-9 h-9 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center text-xs font-bold text-white">B</div></div></nav>);
const bg={background:'linear-gradient(165deg,#080f1c 0%,#0c1a2e 40%,#0f2235 70%,#080f1c 100%)'};
const glass={background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)'};
const pill=(on)=>on?'bg-emerald-500 text-white shadow-lg shadow-emerald-500/20':'text-slate-400 hover:text-slate-200 hover:bg-white/5';
const pillS=(on)=>on?{}:{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.08)'};
if(screen==='home')return(<div className="min-h-screen text-gray-100" style={bg}><Nav/><div className="pt-20">
<div className="relative mx-4 lg:mx-10 rounded-2xl overflow-hidden" style={{minHeight:'420px'}}><div className="absolute inset-0" style={{background:'url(https://images.unsplash.com/photo-1448375240586-882707db888b?w=1400&q=80) center/cover'}}/><div className="absolute inset-0" style={{background:'linear-gradient(180deg,rgba(8,15,28,0.3) 0%,rgba(8,15,28,0.6) 60%,rgba(8,15,28,0.95) 100%)'}}/><div className="relative flex flex-col items-center justify-center text-center px-6 py-24 lg:py-32"><h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-4" style={{fontFamily:"'Playfair Display',Georgia,serif",color:'#a8edce',textShadow:'0 0 80px rgba(52,211,153,0.15)'}}>The Digital Sanctuary</h1><p className="text-slate-300 text-base md:text-lg max-w-xl leading-relaxed">Embark on a journey to discover and identify birds by their unique calls in the wild.</p></div></div>
<div className="grid md:grid-cols-2 gap-4 mx-4 lg:mx-10 mt-6">
<div className="rounded-2xl p-6" style={{...glass,backdropFilter:'blur(12px)'}}><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 4 10 15 15 0 0 1-4 10 15 15 0 0 1-4-10A15 15 0 0 1 12 2z"/></svg></div><h3 className="text-white font-semibold text-lg">Select Region</h3></div><div className="flex flex-wrap gap-2">{R.map(r=>(<button key={r} onClick={()=>setRegion(r)} className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${pill(region===r)}`} style={pillS(region===r)}>{r}</button>))}</div></div>
<div className="rounded-2xl p-6" style={{...glass,backdropFilter:'blur(12px)'}}><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#60a5fa" strokeWidth="2" strokeLinecap="round"><path d="M8 21l4-4 4 4"/><path d="M4 15l8-8 8 8"/></svg></div><h3 className="text-white font-semibold text-lg">Choose Habitat</h3></div><div className="flex flex-wrap gap-2">{H.map(h=>(<button key={h} onClick={()=>setHab(h)} className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${pill(habitat===h)}`} style={pillS(habitat===h)}>{h==='All'?'All Habitats':h}</button>))}</div></div></div>
<div className="mx-4 lg:mx-10 mt-6 rounded-2xl p-6 md:p-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6" style={glass}><div><h2 className="text-2xl md:text-3xl font-bold text-white mb-2" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>Ready for the Expedition?</h2><p className="text-slate-400 text-sm md:text-base">Current settings: <span className="text-emerald-400 font-medium">{region} {habitat==='All'?'':habitat}</span>. We&apos;ve found <span className="text-emerald-400 font-medium">150</span> bird species waiting for your quest.</p></div><button onClick={()=>{setScore(0);setStreak(0);setQn(0);setBest(0);setScreen('play');setTimeout(fetchQ,100);}} className="flex-shrink-0 px-8 py-4 rounded-2xl text-white text-lg font-bold flex items-center gap-3 active:scale-[0.97]" style={{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 8px 32px rgba(16,185,129,0.3)'}}>Start Quest <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button></div>
<div className="flex items-center justify-center gap-4 py-10 text-xs"><span className="text-slate-600 uppercase tracking-widest font-medium">Powered by</span><span className="text-slate-500 font-medium">xeno-canto</span><span className="text-slate-700">|</span><span className="text-slate-500 font-medium">Wikimedia Commons</span></div></div></div>);
return(<div className="min-h-screen text-gray-100" style={bg}><Nav/><div className="pt-24 pb-10 max-w-2xl mx-auto px-4">
{loading&&<div className="text-center py-24"><div className="w-10 h-10 border-[3px] border-emerald-500/20 border-t-emerald-500 rounded-full mx-auto mb-5" style={{animation:'spin .8s linear infinite'}}/><p className="text-slate-400 text-sm">Fetching a real bird call from xeno-canto...</p></div>}
{!loading&&question&&(<div style={{animation:'fadeUp 0.4s ease-out'}}>
<div className="rounded-2xl p-6 text-center mb-5" style={glass}><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500 font-semibold mb-5">Identify this bird call</div><div className="flex justify-center items-center gap-[3px] h-14 mb-5">{Array.from({length:28}).map((_,i)=>(<div key={i} className="w-[3px] rounded-full" style={{background:playing?'#34d399':'rgba(52,211,153,0.15)',height:playing?'100%':'6px',transformOrigin:'center',animation:playing?`pulse-bar ${0.35+Math.random()*0.5}s ease-in-out ${i*0.035}s infinite`:'none'}}/>))}</div>{!audioReady&&!playing&&<p className="text-xs text-slate-500 mb-3">{question.audioUrl?'Loading real recording...':'No recording available'}</p>}<button onClick={playA} disabled={!audioReady} className={`inline-flex items-center gap-3 px-7 py-3 rounded-2xl text-sm font-bold ${playing?'text-emerald-400':audioReady?'text-white':'text-slate-500 cursor-wait'}`} style={playing?{background:'rgba(16,185,129,0.1)',border:'1px solid rgba(16,185,129,0.25)'}:audioReady?{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 6px 24px rgba(16,185,129,0.25)'}:{background:'rgba(255,255,255,0.04)'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">{playing?<><rect x="6" y="4" width="4" height="16" rx="1"/><rect x="14" y="4" width="4" height="16" rx="1"/></>:<polygon points="5,3 19,12 5,21"/>}</svg>{playing?'Pause':audioReady?'Play Call':'Loading...'}</button>{question.recordist&&<p className="text-[11px] text-slate-600 mt-4">\uD83D\uDD0A Recorded by <strong className="text-slate-400">{question.recordist}</strong> \u00b7 xeno-canto \u00b7 {question.license||'CC'}</p>}</div>
{sel===null&&<div className="grid gap-3 mb-5">{question.options.map((o,i)=>(<button key={o.id} onClick={()=>pick(o.id)} className="w-full p-4 rounded-2xl text-left flex items-center gap-4 hover:scale-[1.01] transition-all" style={{background:'rgba(255,255,255,0.025)',border:'1px solid rgba(255,255,255,0.06)'}}><span className="w-10 h-10 rounded-xl flex items-center justify-center text-sm font-bold flex-shrink-0" style={{background:'rgba(96,165,250,0.08)',color:'#60a5fa'}}>{String.fromCharCode(65+i)}</span><span className="font-semibold text-slate-200">{o.en}</span></button>))}</div>}
{sel!==null&&bird&&(<div style={{animation:'fadeUp 0.35s ease-out'}}>
<div className={`flex items-center gap-4 p-4 rounded-2xl mb-5`} style={ok?{background:'rgba(16,185,129,0.08)',border:'1px solid rgba(16,185,129,0.2)'}:{background:'rgba(239,68,68,0.08)',border:'1px solid rgba(239,68,68,0.2)'}}><div className={`w-11 h-11 rounded-full flex items-center justify-center text-white font-bold text-lg ${ok?'bg-emerald-500':'bg-red-500'}`}>{ok?'\u2713':'\u2717'}</div><div><div className={`font-bold text-lg ${ok?'text-emerald-400':'text-red-400'}`}>{ok?(streak>=3?`\uD83D\uDD25 ${streak} in a row!`:'Correct!'):'Not quite!'}</div>{!ok&&<div className="text-sm text-slate-400">Answer: <strong className="text-emerald-400">{bird.en}</strong></div>}</div></div>
<div className="rounded-2xl overflow-hidden mb-5" style={glass}><div className="relative w-full min-h-[220px] flex items-center justify-center" style={{background:'rgba(0,0,0,0.3)'}}>{bird.imageUrl&&!imgErr?(<>{!imgLoaded&&<div className="absolute inset-0 flex items-center justify-center"><div className="w-8 h-8 border-[3px] border-emerald-500/20 border-t-emerald-500 rounded-full" style={{animation:'spin .8s linear infinite'}}/></div>}<img src={bird.imageUrl} alt={bird.en} onLoad={()=>setIL(true)} onError={()=>setIE(true)} className={`w-full max-h-80 object-cover ${imgLoaded?'block':'hidden'}`}/><div className="absolute bottom-0 inset-x-0 px-3 py-1.5" style={{background:'linear-gradient(transparent,rgba(0,0,0,0.6))'}}><p className="text-[10px] text-white/40 text-right">\uD83D\uDCF7 {bird.imageCredit||'Wikimedia'} \u00b7 CC BY-SA</p></div></>):(<div className="py-12 text-slate-600 text-sm">No photo available</div>)}</div>
<div className="p-6"><h2 className="text-2xl font-bold text-white mb-1" style={{fontFamily:"'Playfair Display',Georgia,serif"}}>{bird.en}</h2><p className="text-sm text-blue-400 italic mb-3">{bird.sci}</p><p className="text-sm text-slate-400 leading-relaxed mb-5">{bird.desc}</p>
<div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl" style={{background:'rgba(168,85,247,0.04)',border:'1px solid rgba(168,85,247,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-purple-400 font-bold mb-1">Features</div><div className="text-sm text-slate-300">{bird.features}</div></div><div className="p-3 rounded-xl" style={{background:'rgba(96,165,250,0.04)',border:'1px solid rgba(96,165,250,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-blue-400 font-bold mb-1">Found In</div><div className="text-sm text-slate-300">{bird.regions?.join(' \u00b7 ')}</div></div><div className="p-3 rounded-xl" style={{background:'rgba(52,211,153,0.04)',border:'1px solid rgba(52,211,153,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-emerald-400 font-bold mb-1">Habitat</div><div className="text-sm text-slate-300">{bird.habitats?.map(h=>h.charAt(0).toUpperCase()+h.slice(1)).join(' \u00b7 ')}</div></div><div className="p-3 rounded-xl" style={{background:'rgba(251,191,36,0.04)',border:'1px solid rgba(251,191,36,0.1)'}}><div className="text-[10px] uppercase tracking-[0.15em] text-amber-400 font-bold mb-1">Fun Fact</div><div className="text-sm text-slate-300">{bird.funFact}</div></div></div>{bird.recordist&&<div className="mt-4 pt-4 text-xs text-slate-500" style={{borderTop:'1px solid rgba(255,255,255,0.05)'}}>\uD83D\uDD0A {bird.recordist} \u00b7 xeno-canto \u00b7 {bird.license||'CC'}</div>}</div></div>
<div className="grid gap-2 mb-5">{question.options.map((o,i)=>{const me=o.id===sel,ans=o.id===question.correctId;return(<div key={o.id} className={`flex items-center gap-3 p-3 rounded-xl ${!me&&!ans?'opacity-30':''}`} style={ans?{background:'rgba(16,185,129,0.06)',border:'1px solid rgba(16,185,129,0.2)'}:me&&!ok?{background:'rgba(239,68,68,0.06)',border:'1px solid rgba(239,68,68,0.2)'}:{background:'rgba(255,255,255,0.02)',border:'1px solid rgba(255,255,255,0.04)'}}><span className={`w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold ${ans?'bg-emerald-500 text-white':me&&!ok?'bg-red-500 text-white':'text-slate-500'}`} style={!ans&&!(me&&!ok)?{background:'rgba(255,255,255,0.05)'}:{}}>{ans?'\u2713':me&&!ok?'\u2717':String.fromCharCode(65+i)}</span><span className={`text-sm font-semibold ${ans?'text-emerald-400':'text-slate-400'}`}>{o.en}</span></div>);})}</div>
<button onClick={fetchQ} className="w-full py-4 rounded-2xl text-white font-bold text-lg flex items-center justify-center gap-2 active:scale-[0.97]" style={{background:'linear-gradient(135deg,#10b981,#34d399)',boxShadow:'0 8px 32px rgba(16,185,129,0.25)'}}>Next Question <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button>
<div className="flex justify-center gap-8 mt-5 p-4 rounded-xl" style={{background:'rgba(255,255,255,0.02)'}}>{[{l:'Accuracy',v:(qn?Math.round(score/qn*100):0)+'%',c:'text-slate-200'},{l:'Best Streak',v:best,c:'text-amber-400'},{l:'Total',v:qn,c:'text-blue-400'}].map((x,i)=>(<div key={i} className="text-center"><div className="text-[10px] uppercase tracking-wider text-slate-600">{x.l}</div><div className={`text-lg font-bold ${x.c}`}>{x.v}</div></div>))}</div>
<button onClick={()=>{if(ar.current)ar.current.pause();setScreen('home');}} className="w-full mt-4 py-3 rounded-xl text-slate-400 text-sm font-medium hover:text-slate-200" style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.06)'}}>\u2190 Back to Sanctuary</button>
</div>)}</div>)}</div></div>);}
