// Bird database with pre-cached xeno-canto recording IDs
// Audio served via xeno-canto embed player URLs
export const BIRDS=[
{id:1,en:"Indian Peafowl",sci:"Pavo cristatus",regions:["Asia","India"],habitats:["forest","grassland","urban"],desc:"National bird of India with iridescent blue-green plumage and spectacular tail display.",funFact:"A peacock's tail feathers can span up to 6 feet wide.",difficulty:"common",features:"Iridescent blue neck, ornate eyespot tail train",xcId:"21756",xcRec:"Gopinath Sricandane",xcLic:"CC BY-NC-ND 2.5"},
{id:2,en:"Indian Roller",sci:"Coracias benghalensis",regions:["Asia","India"],habitats:["grassland","urban","forest"],desc:"Strikingly colorful bird known for acrobatic rolling courtship flights.",funFact:"Performs mid-air rolls and dives hence its name.",difficulty:"common",features:"Vivid blue wings, turquoise breast, brown back",xcId:"307498",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:3,en:"Common Myna",sci:"Acridotheres tristis",regions:["Asia","India","Oceania"],habitats:["urban","grassland"],desc:"Bold noisy bird with bright yellow eye patches found across Indian cities.",funFact:"Can mimic human speech; one of the worlds most invasive species.",difficulty:"common",features:"Brown body, black head, yellow eye patch",xcId:"247498",xcRec:"Frank Lambert",xcLic:"CC BY-NC-SA 4.0"},
{id:4,en:"Red-vented Bulbul",sci:"Pycnonotus cafer",regions:["Asia","India"],habitats:["forest","urban","grassland"],desc:"Perky songbird with a distinctive crest and red patch under the tail.",funFact:"One of the first birds singing at dawn in Indian gardens.",difficulty:"common",features:"Black crested head, dark brown body, red vent",xcId:"268775",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:5,en:"Asian Koel",sci:"Eudynamys scolopaceus",regions:["Asia","India","Oceania"],habitats:["forest","urban"],desc:"Famous for its loud rising call heard during breeding season.",funFact:"Brood parasite - lays eggs in crow nests.",difficulty:"common",features:"Male: glossy black. Female: brown spotted",xcId:"253498",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:6,en:"Rose-ringed Parakeet",sci:"Psittacula krameri",regions:["Asia","India","Africa","Europe"],habitats:["forest","urban"],desc:"Bright green parrot with rose-colored neck ring in males.",funFact:"Feral populations in 35+ countries worldwide.",difficulty:"common",features:"Bright green, red beak, rose-black neck ring",xcId:"298267",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:7,en:"White-throated Kingfisher",sci:"Halcyon smyrnensis",regions:["Asia","India"],habitats:["wetland","urban","forest"],desc:"Large kingfisher with vivid turquoise wings and chocolate-brown head.",funFact:"Often hunts far from water eats lizards insects.",difficulty:"common",features:"Turquoise wings, brown head, white throat, red bill",xcId:"327890",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:8,en:"Black Drongo",sci:"Dicrurus macrocercus",regions:["Asia","India"],habitats:["grassland","urban","forest"],desc:"Glossy black bird with forked tail, fearlessly territorial.",funFact:"Attacks raptors much larger than itself called King Crow.",difficulty:"common",features:"Glossy black, deeply forked tail, red eye",xcId:"251833",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:9,en:"Spotted Owlet",sci:"Athene brama",regions:["Asia","India"],habitats:["urban","forest"],desc:"Small stocky owl with white spots, common near human habitation.",funFact:"Highly vocal at dusk with a wide variety of calls.",difficulty:"common",features:"Gray-brown, white spots, large yellow eyes",xcId:"276553",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:10,en:"Indian Golden Oriole",sci:"Oriolus kundoo",regions:["Asia","India"],habitats:["forest","urban"],desc:"Stunning bright yellow bird with black eye-stripe.",funFact:"Its flute-like whistle is among the most beautiful forest sounds.",difficulty:"common",features:"Golden-yellow, black eye-stripe, pinkish bill",xcId:"414037",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:11,en:"Purple Sunbird",sci:"Cinnyris asiaticus",regions:["Asia","India"],habitats:["forest","urban"],desc:"Tiny nectar-feeder; breeding males shimmer metallic purple.",funFact:"Hovers like a hummingbird while feeding on nectar.",difficulty:"common",features:"Male: metallic purple-black. Female: olive-yellow",xcId:"258756",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:12,en:"Coppersmith Barbet",sci:"Psilopogon haemacephalus",regions:["Asia","India"],habitats:["forest","urban"],desc:"Named for its tuk-tuk-tuk call like a coppersmith hammering.",funFact:"Repeats its metronomic call 100+ times per minute.",difficulty:"common",features:"Green body, crimson forehead, yellow throat",xcId:"287710",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:13,en:"Indian Grey Hornbill",sci:"Ocyceros birostris",regions:["Asia","India"],habitats:["forest","urban"],desc:"Large grey bird with distinctive curved bill and casque.",funFact:"Females seal themselves inside tree hollows during nesting.",difficulty:"common",features:"Grey plumage, large curved casqued bill",xcId:"206889",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:14,en:"Painted Stork",sci:"Mycteria leucocephala",regions:["Asia","India"],habitats:["wetland"],desc:"Large wading bird with pink feathers and orange face.",funFact:"Fishes by touch walks with open bill submerged.",difficulty:"common",features:"White, black bars, pink feathers, orange face",xcId:"281966",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:15,en:"Greater Coucal",sci:"Centropus sinensis",regions:["Asia","India"],habitats:["forest","grassland","urban"],desc:"Large crow-sized bird with deep booming calls.",funFact:"Its call is considered a good omen in Indian folklore.",difficulty:"common",features:"Black head, chestnut wings, long tail",xcId:"262180",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:16,en:"Common Tailorbird",sci:"Orthotomus sutorius",regions:["Asia","India"],habitats:["urban","forest"],desc:"Tiny warbler that sews leaves together for its nest.",funFact:"Uses its bill as a needle with spider silk as thread.",difficulty:"common",features:"Olive-green, rusty crown, long upright tail",xcId:"310890",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:17,en:"House Sparrow",sci:"Passer domesticus",regions:["Asia","India","Europe","Americas","Africa"],habitats:["urban"],desc:"One of the most widespread birds near human settlements.",funFact:"Populations declined 80% in many Indian cities since 2000.",difficulty:"common",features:"Male: grey crown, black bib. Female: plain brown",xcId:"416328",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:18,en:"Sarus Crane",sci:"Antigone antigone",regions:["Asia","India"],habitats:["wetland","grassland"],desc:"Worlds tallest flying bird at 6 feet. Lifelong pair bonds.",funFact:"Pairs dance and trumpet in unison with heads thrown back.",difficulty:"rare",features:"Tall grey, red head and upper neck",xcId:"284665",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:19,en:"Indian Pitta",sci:"Pitta brachyura",regions:["Asia","India"],habitats:["forest"],desc:"Brilliantly multi-colored ground-dwelling bird.",funFact:"Despite vivid colors nearly invisible on dappled forest floor.",difficulty:"rare",features:"Green, blue, orange, buff, black, white",xcId:"316775",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:20,en:"Great Indian Bustard",sci:"Ardeotis nigriceps",regions:["Asia","India"],habitats:["grassland"],desc:"Critically endangered; one of the heaviest flying birds.",funFact:"Fewer than 150 remain in the wild.",difficulty:"rare",features:"Large brown-white body, black crown, long legs",xcId:"306143",xcRec:"Nikhil Devasar",xcLic:"CC BY-NC-SA 4.0"},
{id:21,en:"Hoopoe",sci:"Upupa epops",regions:["Europe","Asia","Africa","India"],habitats:["grassland","urban"],desc:"Distinctive bird with dramatic fan-shaped crest.",funFact:"Chicks spray foul-smelling liquid at predators.",difficulty:"common",features:"Cinnamon body, black-white striped crest",xcId:"467188",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:22,en:"Common Nightingale",sci:"Luscinia megarhynchos",regions:["Europe","Asia","Africa"],habitats:["forest","wetland"],desc:"Famous for powerful beautiful song heard at night.",funFact:"Produces over 1000 different sounds.",difficulty:"common",features:"Plain brown, lighter below, rufous tail",xcId:"405884",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:23,en:"European Robin",sci:"Erithacus rubecula",regions:["Europe","Asia"],habitats:["forest","urban"],desc:"Small passerine with distinctive orange-red breast.",funFact:"So territorial it attacks its own reflection.",difficulty:"common",features:"Orange-red breast, olive-brown upper parts",xcId:"604587",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:24,en:"Bald Eagle",sci:"Haliaeetus leucocephalus",regions:["Americas"],habitats:["wetland","forest"],desc:"Powerful raptor, national bird of the United States.",funFact:"Dives at 100 mph; nests weigh over 2 tons.",difficulty:"common",features:"White head/tail, dark body, yellow bill",xcId:"308880",xcRec:"Paul Marvin",xcLic:"CC BY-NC-SA 4.0"},
{id:25,en:"Laughing Kookaburra",sci:"Dacelo novaeguineae",regions:["Oceania"],habitats:["forest","urban"],desc:"Known for its loud distinctive laughing call.",funFact:"Its laugh is a stock jungle sound in Hollywood movies.",difficulty:"common",features:"Large head, brown eye-stripe, blue wings",xcId:"322441",xcRec:"Marc Anderson",xcLic:"CC BY-NC-ND 4.0"},
{id:26,en:"Tawny Owl",sci:"Strix aluco",regions:["Europe","Asia"],habitats:["forest","urban"],desc:"Classic twit-twoo owl of European woodlands.",funFact:"The twit-twoo is a duet between male and female.",difficulty:"common",features:"Mottled brown, large dark eyes, round face",xcId:"456878",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:27,en:"Common Kingfisher",sci:"Alcedo atthis",regions:["Europe","Asia","Africa","India"],habitats:["wetland"],desc:"Brilliantly colored bird that plunge-dives for fish.",funFact:"Japans bullet train was redesigned based on its beak.",difficulty:"common",features:"Electric blue above, orange below, dagger bill",xcId:"462232",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:28,en:"Greater Flamingo",sci:"Phoenicopterus roseus",regions:["Europe","Africa","Asia","India"],habitats:["wetland","coastal"],desc:"Largest flamingo, massive flocks at Indian salt lakes.",funFact:"Pink color comes from carotenoids in their food.",difficulty:"common",features:"Pink plumage, curved neck, black-tipped bill",xcId:"322975",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"},
{id:29,en:"Barn Swallow",sci:"Hirundo rustica",regions:["Europe","Asia","Americas","Africa","India"],habitats:["urban","grassland"],desc:"Most widespread swallow with deeply forked tail.",funFact:"Drinks water while flying by skimming pond surfaces.",difficulty:"common",features:"Blue-black above, rust-red throat, forked tail",xcId:"477651",xcRec:"Jarek Matusiak",xcLic:"CC BY-NC-SA 4.0"},
{id:30,en:"Snowy Owl",sci:"Bubo scandiacus",regions:["Europe","Americas","Asia"],habitats:["grassland"],desc:"Large white owl of the Arctic tundra.",funFact:"Unlike most owls, hunts primarily during daylight.",difficulty:"common",features:"White with dark barring, bright yellow eyes",xcId:"192220",xcRec:"Tero Linjama",xcLic:"CC BY-NC-SA 3.0"},
{id:31,en:"Emperor Penguin",sci:"Aptenodytes forsteri",regions:["Global"],habitats:["coastal"],desc:"Tallest and heaviest of all living penguins.",funFact:"Males incubate eggs on feet for 65 days at minus 60C.",difficulty:"common",features:"Black back, white belly, yellow-orange patches",xcId:"226463",xcRec:"Frank Lambert",xcLic:"CC BY-NC-SA 4.0"},
{id:32,en:"Scarlet Macaw",sci:"Ara macao",regions:["Americas"],habitats:["forest"],desc:"Brilliantly colored parrot from Central/South American tropics.",funFact:"Can live up to 75 years and mate for life.",difficulty:"common",features:"Red body, blue/yellow wings, long tail",xcId:"299401",xcRec:"Peter Boesman",xcLic:"CC BY-NC-ND 4.0"}
];
export const REGIONS=["Global","India","Asia","Europe","Africa","Americas","Oceania"];
export const HABITATS=["All","forest","wetland","urban","grassland","coastal"];
